src/lib.rs
The trait MailHeaderMap has two methods for searching headers, normal
and case-insensitive. This documentation says:
> According to the spec the mail headers are supposed to be
> case-sensitive, but in real-world scenarios that's not always the
> case.
Actually, the spec says nothing that headers supposed to case-sensitive,
and historical precedent is to be case-insensitive. Certainly, all the
mail processing software I am familiar with (Thunderbird, qmail, ezmlm,
and mutt) treat headers as case insensitive. RFC 822 section 3.4.7 says:
> When matching any other syntactic unit, case is to be ignored. For
> example, the field-names "From", "FROM", "from", and even "FroM" are
> semantically equal and should all be treated identically.
While RFC 2822 did drop that section (and RFC 5322 didn't …
=> Make MailHeaderMap perform case-insensitive searches

src/lib.rs
Tests where even showing that this parsing was wrong. You would not expect `q uick survey` but `quick survey` from the test. Proposed for fixing #19.
=> MailHeader::get_value: do not add space if special char parsed

src/dateparse.rs, src/lib.rs
This leaves precisely one clippy warning:
```
warning: length comparison to zero
--> src/lib.rs:110:13
|
110 |     assert!(key.len() > 0);
|             ^^^^^^^^^^^^^ help: using `is_empty` is more concise: `!key.is_empty()`
|
= note: #[warn(len_zero)] on by default
= help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#len_zero
```
Not sure I agree with clippy in this particular case.
=> Fix a variety of clippy lint warnings

src/lib.rs, src/macros.rs
Removes use of `try!` and `try_none!`, amongst various other cleanups.
7eda2c0 slightly changes base64 handling: vertical tabs weren't getting stripped.  I think this is reasonable.
=> Tidy Result/Option use

src/lib.rs
=> key.len() > 0 -> !key.is_empty()

README.md
it appears these are in reverse order - docs.rs is obviously not a valid url
=> fixing docs.rs link

src/lib.rs
Currently, if there is a new line in params values
```
Content-Type: application/octet-stream; name="
"
```
mailparse will panic with no chance to recover (due to indexing without boundary checks).
This PR simply adds a check to be sure it does not panic, though it will still return garbage.
=> Fix panic when encountering param content with new line

Cargo.toml, src/lib.rs
[`charset`](https://crates.io/crates/charset) is a crate that provides Thunderbird-compatible decoding of character encodings in email by implementing UTF-7 and wrapping [`encoding_rs`](https://crates.io/crates/encoding_rs) for the rest. (Thunderbird uses encoding_rs for non-UTF-7 encodings.)
This PR replaces the dependency on `encoding` with a dependency on `charset`. Apart from performance differences, the only observable behavior changes should be 1) the addition of UTF-7 support, 2) the removal of HZ support, 3) honoring the BOM in email bodies (unclear if appropriate), and 4) a spec change to the mapping of one byte in windows-1255 (Hebrew). Experience from Thunderbird and the Firefox OS email client suggests that UTF-7 decode support is still need. (But Thunderbird has gotten away …
=> Add UTF-7 support by using the charset crate instead of the encoding crate

src/addrparse.rs
This adds the ability to consume the inner MailAddrs and thus let's
users avoid clones in some scenarios.
=> Add into_inner to MailAddrList

src/addrparse.rs
Specifically, in the previous implementation the iterator implementation
of `HeaderTokenItem` would start iterating over all chars of a `Text`
from the beginning for every call to `next`. This was (naturally)
particularly noticeable when parsing larger to/cc/bcc headers.
=> Fix quadratic behavior of addrparse

Cargo.toml
See also #67, except this is the latest one, all tests passed locally. 
There is no reason other than to minimize the dependency tree and to get rid of the following issues when used along other crates such as latest `imap`:
```console
$ cargo doc
warning: output filename collision.
The lib target `base64` in package `base64 v0.12.2` has the same output filename as the lib target `base64` in package `base64 v0.10.1`.
Colliding filename is: /home/user/projects/mail/target/doc/base64/index.html
$ cargo clippy
warning: multiple versions for dependency `base64`: 0.10.1, 0.11.0, 0.12.2
```
=> updates base64 dependency

src/msgidparse.rs
Closes #72 
This PR:
- adds a benchmark using [criterion](https://github.com/bheisler/criterion.rs) for the current `msgidparse` function
- covers the existing `msgidparse` function with unit tests
- updates the implementation of `msgidparse` to make separator whitespace optional, as per  [RFC5322](https://tools.ietf.org/html/rfc5322#section-3.6.4) 
**No significant decrease** in speed was seen for short or long inputs to `msgidparse`.
```log
msgidparse single id    time:   [74.461 ns 74.700 ns 74.958 ns]
msgidparse many ids     time:   [8.0999 us 8.1436 us 8.1853 us]
```
```log
msgidparse single id    time:   [75.269 ns 75.839 ns 76.397 ns]
change: [+0.1514% +0.8757% +1.6172%] (p = 0.02 < 0.05)
Change within noise threshold.
msgidparse many ids     time:   [8.1968 us 8.2692 us 8.3627 us] …
```
=> msgidparse: make whitespace separating message ids optional

src/headers.rs, src/lib.rs
In order to allow better formatting and printing of `Headers`, add custom
Debug traits that convert `MailHeader` items into legible strings and
allow printing the content of `Headers` struct.
Addresses issue #83
=> Add custom Debug trait for Headers and MailHeader

src/lib.rs
This is needed to calculate detached OpenPGP signatures over message parts. The signature is calculated over both the headers and the body according to https://datatracker.ietf.org/doc/html/rfc1847
=> Expose raw_bytes of parts in the public API

Cargo.toml, src/body.rs, src/header.rs, src/lib.rs
This has the main benefit of supporting concatenated base64 strings that
frequently occur within emails.
See
https://github.com/ia0/data-encoding/blob/master/lib/src/lib.rs#L2266-L2283
for details on the implementation.
=> Switch base64 implementation to data_encoding

Cargo.toml
This removes the `byteorder` dependency and gets both libraries on the same `base64`
Thanks for this library! It's a key component to a project I'm working on, [crabmail](https://git.alexwennerberg.com/crabmail/)
=> Upgrade charset to v0.1.3

Cargo.toml, src/lib.rs
There was a change in behaviour in quoted-printable 0.4.7 which caused one of the doc-tests to fail. This updates the minimum quoted-printable version and updates the doc-test to match the new (more correct) behaviour.
Fixes #119.
=> Upgrade to quoted-printable 0.4.8

Cargo.toml, src/body.rs, src/header.rs
This uses the updated data-encoding crate that introduced the new functionality in https://github.com/ia0/data-encoding/pull/104
=> Use BASE64_MIME_PERMISSIVE to allow trailing bits in b64 data

src/lib.rs
=> Treat crlf before boundary as part of the boundary

src/lib.rs
Fixes https://github.com/staktrace/mailparse/issues/130
=> fix: don't panic if multipart message has no starting boundary
